global:
  scrape_interval:     5s 
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    #- targets: ['localhost:9090']
    #- targets: ['docker.for.win.localhost:9090']
    - targets: ['docker.for.mac.localhost:9090']
        
  - job_name: 'xlator'
    metrics_path: '/actuator/prometheus'
    static_configs:
    #- targets: ['localhost:80']
    #- targets: ['docker.for.win.localhost:80']
    - targets: ['docker.for.mac.localhost:80']
      labels:
        application: xlator-service