# MASTER CONFIGURATION
# Be sure to register for an account on http://frengly.com before attempting to use this service!
# You should update the configuration below, uncommenting email and password and entering appropriate values matching a valid pair of credentials. 

app:
  frengly:
    #email: 
    #password: 
  defaults:
    locale: en
  info:
    version: @project.version@
  limits:
    translationsPerRequest: 50