# MASTER CONFIGURATION
***REMOVED***
# You should update the configuration below, uncommenting email and password and entering appropriate values matching a valid pair of credentials.
***REMOVED***
# Update the configuration below to add your API key.  Be sure to update the app.defaults.service key to google if you wish to employ the Google Translate API instead.

app:
  #frengly:
    #email: 
    #password: 
  #google:
    #key:
  defaults:
    # service options are: frengly (the default) or google (if updated)
    service: frengly
  info:
    version: @project.version@
