# MASTER CONFIGURATION
***REMOVED***
# You should update the configuration below, uncommenting email and password and entering appropriate values matching a valid pair of credentials.
***REMOVED***
# Update the configuration below to add your API key.  Be sure to update the app.defaults.service key to google if you wish to employ the Google Translate API instead.

app:
  cache:
    provider: local
  #frengly:
    #email: 
    #password: 
  #google:
    #key:
  defaults:
    locale: en
    # service options are: frengly (the default) or google (if updated)
    service: frengly
  info:
    version: @project.version@
  limits:
    translationsPerRequest: 100

spring:
  application:
    name: @project.artifactId@
  autoconfigure: 
    exclude:
      - org.springframework.boot.actuate.autoconfigure.CacheStatisticsAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.cache.ElastiCacheAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
     
logging:
  level:
    - org.springframework.web: INFO
    - com.fns.xlator: INFO
    
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,httptrace,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 50ms 
 
---

spring:
  profiles: docker
  profiles.include: redis
  redis:
    host: redis
        
---

spring:
  profiles: aws
  profiles.include: redis
          
---

spring:
  profiles: redis
  
app:
  cache:
    provider: redis
    